name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: C Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Build
        run: |
          autoreconf --install
          ./configure
          make 
          make check
